AWSTemplateFormatVersion: 2010-09-09

Description: A preencher

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Route Table"
        Parameters:
          - IDPeering
          - DestinationCIDR

    ParameterLabels:
      IDPeering:
        default: "Input ID VPC Peering"
      DestinationCIDR:
        default: "Input CIDR of Requester"

Parameters:
  
  IDPeering:
    Type: String

  DestinationCIDR:
    Type: String

Resources:

    RouteTable1:
      Type: AWS::EC2::Route
      Properties: 
        RouteTableId: rtb-xxxxxxxxxx
        DestinationCidrBlock: !Ref DestinationCIDR
        VpcPeeringConnectionId: !Ref IDPeering

    RouteTable2:
      Type: AWS::EC2::Route
      Properties: 
        RouteTableId: rtb-xxxxxxxxxx
        DestinationCidrBlock: !Ref DestinationCIDR
        VpcPeeringConnectionId: !Ref IDPeering

    RouteTable3:
      Type: AWS::EC2::Route
      Properties: 
        RouteTableId: rtb-xxxxxxxxxx
        DestinationCidrBlock: !Ref DestinationCIDR
        VpcPeeringConnectionId: !Ref IDPeering